// =============================================================================
// gen_glyph_advance.ts — 埋め込みフォント (fonts/ipaexg.ttf) の実 glyph advance 幅を
// パースし、非 1.0 em の codepoint→advance(em) 例外テーブルを src/glyph_advance.ts へ出力する。
// -----------------------------------------------------------------------------
// 幅モデルを「全角1.0/半角0.5」ヒューリスティックから実描画(実 advance)基準へ揃えるための
// 生成物。CJK/かなは実測で一律 1.0 em のため既定 1.0 とし、ASCII/数字/記号/半角カナ等の
// 非 1.0 グリフのみを例外として持つ (= 小サイズ)。フォントを差し替えたら本スクリプトを再実行する。
//   実行: npm run gen:widths
// 依存追加なし (最小 TrueType パーサ: head/hhea/hmtx/cmap fmt4(3,1)+fmt12)。
// =============================================================================

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_PATH = path.join(ROOT, "fonts", "ipaexg.ttf");
const OUT_PATH = path.join(ROOT, "src", "glyph_advance.ts");

const b = fs.readFileSync(FONT_PATH);
const u16 = (o: number) => b.readUInt16BE(o);
const u32 = (o: number) => b.readUInt32BE(o);

const numTables = u16(4);
const tbl: Record<string, number> = {};
for (let i = 0; i < numTables; i += 1) {
  const o = 12 + i * 16;
  tbl[b.toString("latin1", o, o + 4)] = u32(o + 8);
}

const unitsPerEm = u16(tbl.head + 18);
const numHM = u16(tbl.hhea + 34);
const hmtx = tbl.hmtx;
const advEm = (gid: number) => u16(hmtx + Math.min(gid, numHM - 1) * 4) / unitsPerEm;

// cmap: format 4 (3,1) を主、format 12 を補助として全マップ codepoint を列挙する。
const cmapOff = tbl.cmap;
const nSub = u16(cmapOff + 2);
const subs: { pid: number; eid: number; off: number; fmt: number }[] = [];
for (let i = 0; i < nSub; i += 1) {
  const o = cmapOff + 4 + i * 8;
  const off = cmapOff + u32(o + 4);
  subs.push({ pid: u16(o), eid: u16(o + 2), off, fmt: u16(off) });
}
const f4 = subs.find((s) => s.pid === 3 && s.eid === 1 && s.fmt === 4);
const f12 = subs.find((s) => s.fmt === 12);

const codeToGid = new Map<number, number>();
if (f4) {
  const base = f4.off;
  const segX2 = u16(base + 6);
  const segCount = segX2 / 2;
  const endO = base + 14;
  const startO = endO + segX2 + 2;
  const deltaO = startO + segX2;
  const rangeO = deltaO + segX2;
  for (let s = 0; s < segCount; s += 1) {
    const end = u16(endO + s * 2);
    const st = u16(startO + s * 2);
    const delta = u16(deltaO + s * 2);
    const ro = u16(rangeO + s * 2);
    for (let cp = st; cp <= end && cp !== 0xffff; cp += 1) {
      let gid: number;
      if (ro === 0) gid = (cp + delta) & 0xffff;
      else {
        const gi = u16(rangeO + s * 2 + ro + (cp - st) * 2);
        gid = gi === 0 ? 0 : (gi + delta) & 0xffff;
      }
      if (gid !== 0) codeToGid.set(cp, gid);
    }
  }
}
if (f12) {
  const base = f12.off;
  const nGroups = u32(base + 12);
  for (let g = 0; g < nGroups; g += 1) {
    const o = base + 16 + g * 12;
    const start = u32(o);
    const end = u32(o + 4);
    const sg = u32(o + 8);
    for (let cp = start; cp <= end; cp += 1) {
      if (!codeToGid.has(cp)) codeToGid.set(cp, sg + (cp - start));
    }
  }
}

// 非 1.0 em の codepoint のみ例外として記録 (4 桁丸め)。CJK/かなは実測 1.0 なので既定で省く。
const entries: [number, number][] = [];
for (const [cp, gid] of [...codeToGid.entries()].sort((a, b2) => a[0] - b2[0])) {
  const em = Math.round(advEm(gid) * 10000) / 10000;
  if (em !== 1) entries.push([cp, em]);
}

const lines = entries.map(([cp, em]) => `  [0x${cp.toString(16)}, ${em}],`);
const out = `// AUTO-GENERATED by scripts/gen_glyph_advance.ts — DO NOT EDIT BY HAND.
// 埋め込みフォント fonts/ipaexg.ttf (unitsPerEm=${unitsPerEm}) の実 glyph advance(em)。
// 非 1.0 em の codepoint のみ収録 (CJK/かなは実測一律 1.0 のため既定 1.0)。
// フォント差し替え時は \`npm run gen:widths\` で再生成する。
// 収録数: ${entries.length}
export const GLYPH_ADVANCE_EM: ReadonlyMap<number, number> = new Map<number, number>([
${lines.join("\n")}
]);
`;
fs.writeFileSync(OUT_PATH, out, "utf-8");
console.log(`wrote ${OUT_PATH}: ${entries.length} non-1.0 entries (unitsPerEm=${unitsPerEm})`);
